# Session - 4 Data Processing Part 2

In [165]:
import pandas as pd
import numpy as np

# Task 1.
Download a small dataset of IPL cricket player stats (e.g., runs, wickets, matches, strike rate) and apply StandardScaler from scikit-learn to scale all numeric features. Save the scaled data to a new CSV file named ipl_scaled.csv.

In [166]:
df = pd.read_csv(r"C:\Users\DHRUV MODI\Documents\TOPS\Data set\ipl_player_data.csv")

In [167]:
df.head()

      player_name  player_age team                   venue player_role
0     Virat Kohli        35.0  RCB  M. Chinnaswamy Stadium     Batsman
1        MS Dhoni        42.0  CSK  MA Chidambaram Stadium     Batsman
2    Rohit Sharma        36.0   MI        Wankhede Stadium     Batsman
3  Jasprit Bumrah         NaN   MI        Wankhede Stadium      Bowler
4        KL Rahul        31.0  LSG   Ekana Cricket Stadium     Batsman

In [168]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   player_name  15 non-null     str
 1   player_age   12 non-null     float64
 2   team         13 non-null     str
 3   venue        15 non-null     str
 4   player_role  15 non-null     str
dtypes: float64(1), str(4)
memory usage: 1.3 KB

In [169]:
df.isnull().sum()

player_name    0
player_age     3
team           2
venue          0
player_role    0
dtype: int64

In [170]:
df.dropna(inplace=True)

In [171]:
from sklearn.preprocessing import StandardScaler

In [172]:
scaler = StandardScaler()

In [173]:
df['player_age'] = scaler.fit_transform(df[['player_age']])

In [174]:
df.head()

     player_name  player_age team                   venue player_role
0    Virat Kohli    0.215666  RCB  M. Chinnaswamy Stadium     Batsman
1       MS Dhoni    2.102739  CSK  MA Chidambaram Stadium     Batsman
2   Rohit Sharma    0.485247   MI        Wankhede Stadium     Batsman
4       KL Rahul   -0.862662  LSG   Ekana Cricket Stadium     Batsman
5  Hardik Pandya   -1.132244   GT   Narendra Modi Stadium  Allrounder

# Task 2.
Using a dataset of Flipkart product ratings (features: price, rating, number of reviews, discount), apply MinMaxScaler so that all features are scaled between 0 and 1. Print the minimum and maximum value for each column before and after scaling.<br><br><em><strong>Hint:</strong> Use pandas to load the data and scikit-learn's MinMaxScaler for scaling.</em>

In [175]:
df = pd.read_csv(r"C:\Users\DHRUV MODI\Documents\TOPS\Data set\flipkart_product.csv\flipkart_product.csv",encoding='Latin1')
df.head()

,ProductName,Price,Rate,Review,Summary
0,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",5,Super!,Great cooler.. excellent air flow and for this...
1,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",5,Awesome,Best budget 2 fit cooler. Nice cooling
2,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",3,Fair,The quality is good but the power of air is de...
3,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",1,Useless product,Very bad product it's a only a fan
4,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",3,Fair,Ok ok product

In [176]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 189874 entries, 0 to 189873
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   ProductName  189874 non-null  str
 1   Price        189873 non-null  str
 2   Rate         189873 non-null  str
 3   Review       189870 non-null  str
 4   Summary      189860 non-null  str
dtypes: str(5)
memory usage: 35.3 MB

In [177]:
df['Price'] = pd.to_numeric(df['Price'].str.replace(r'[^\d]', '', regex=True), errors='coerce')
df['Rate'] = pd.to_numeric(df['Rate'], errors='coerce')

In [178]:
df.head()

,ProductName,Price,Rate,Review,Summary
0,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,3999.0,5.0,Super!,Great cooler.. excellent air flow and for this...
1,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,3999.0,5.0,Awesome,Best budget 2 fit cooler. Nice cooling
2,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,3999.0,3.0,Fair,The quality is good but the power of air is de...
3,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,3999.0,1.0,Useless product,Very bad product it's a only a fan
4,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,3999.0,3.0,Fair,Ok ok product

In [179]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 189874 entries, 0 to 189873
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   ProductName  189874 non-null  str
 1   Price        189873 non-null  float64
 2   Rate         189869 non-null  float64
 3   Review       189870 non-null  str
 4   Summary      189860 non-null  str
dtypes: float64(2), str(3)
memory usage: 33.4 MB

In [180]:
df = df.dropna()

In [181]:
print(df.min())
print("-----------------")
print(df.max())

ProductName    1170-BL-BR Unique New Day & Date Analog Watch ...
Price                                                       59.0
Rate                                                         1.0
Review                                 "Wise deal for the price"
Summary         " Samsung" always perfect and Love you..........
dtype: object
-----------------
ProductName    wood city handicrafts wooden round side coffee...
Price                                                    86990.0
Rate                                                         5.0
Review                                             wrost product
Summary                                  ð¥³ð¥³ super se uper.
dtype: object

In [182]:
from sklearn.preprocessing import MinMaxScaler

In [183]:
scaler = MinMaxScaler()

In [184]:
df[['Price', 'Rate']] = scaler.fit_transform(df[['Price', 'Rate']])

In [185]:
df.head()

,ProductName,Price,Rate,Review,Summary
0,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,0.045323,1.0,Super!,Great cooler.. excellent air flow and for this...
1,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,0.045323,1.0,Awesome,Best budget 2 fit cooler. Nice cooling
2,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,0.045323,0.5,Fair,The quality is good but the power of air is de...
3,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,0.045323,0.0,Useless product,Very bad product it's a only a fan
4,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,0.045323,0.5,Fair,Ok ok product

In [186]:
print(df.min())
print("-----------------")
print(df.max())

ProductName    1170-BL-BR Unique New Day & Date Analog Watch ...
Price                                                        0.0
Rate                                                         0.0
Review                                 "Wise deal for the price"
Summary         " Samsung" always perfect and Love you..........
dtype: object
-----------------
ProductName    wood city handicrafts wooden round side coffee...
Price                                                        1.0
Rate                                                         1.0
Review                                             wrost product
Summary                                  ð¥³ð¥³ super se uper.
dtype: object

# Task 3.
Given a Spotify songs dataset (features: danceability, energy, tempo, popularity), use correlation analysis to select the top 2 features most related to 'popularity'. List the selected features and explain your choice in one line each.

In [188]:
df = pd.read_csv(r"C:\Users\DHRUV MODI\Documents\TOPS\Data set\Spotify top 50 songs\Spotify top 50 songs.csv",encoding='Latin')
df.head()

,Column1,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
0,1,SeÃ±orit,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79
1,2,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92
2,3,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85
3,4,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,86
4,5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94

In [189]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Column1           50 non-null     int64
 1   Track.Name        50 non-null     str
 2   Artist.Name       50 non-null     str
 3   Genre             50 non-null     str
 4   Beats.Per.Minute  50 non-null     int64
 5   Energy            50 non-null     int64
 6   Danceability      50 non-null     int64
 7   Loudness..dB..    50 non-null     int64
 8   Liveness          50 non-null     int64
 9   Valence.          50 non-null     int64
 10  Length.           50 non-null     int64
 11  Acousticness..    50 non-null     int64
 12  Speechiness.      50 non-null     int64
 13  Popularity        50 non-null     int64
dtypes: int64(11), str(3)
memory usage: 7.4 KB

In [190]:
numeric_df = df.select_dtypes(include=['float64', 'int64'])

In [191]:
corr = numeric_df.corr()['Popularity']

In [192]:
corr

Column1            -0.160680
Beats.Per.Minute    0.196097
Energy             -0.080295
Danceability       -0.071413
Loudness..dB..     -0.043085
Liveness            0.092564
Valence.           -0.317752
Length.            -0.087639
Acousticness..     -0.034684
Speechiness.        0.238553
Popularity          1.000000
Name: Popularity, dtype: float64

# Task 4.
Take a Zomato restaurant dataset and use scikit-learn's RFE (Recursive Feature Elimination) with a DecisionTreeRegressor to select the 3 most important features for predicting 'average cost for two'. List the selected features and the RFE ranking.

In [193]:
df = pd.read_csv(r"C:\Users\DHRUV MODI\Documents\TOPS\Data set\zomato restaurant.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur

In [194]:
df['online_order'] = df['online_order'].map({'Yes': 1, 'No': 0})
df['table booking'] = df['table booking'].map({'Yes': 1, 'No': 0})

In [196]:
df.dropna(inplace=True)

In [197]:
X = df[['rate (out of 5)', 'num of ratings', 'online_order', 'table booking']]
y = df['avg cost (two people)']

In [198]:
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeRegressor

In [199]:
model = DecisionTreeRegressor()

In [200]:
rfe = RFE(estimator=model, n_features_to_select=3)
rfe.fit(X, y)

RFE(estimator=DecisionTreeRegressor(), n_features_to_select=3)

In [203]:
X.columns

Index(['rate (out of 5)', 'num of ratings', 'online_order', 'table booking'], dtype='str')

In [206]:
rfe.ranking_

array([1, 1, 2, 1])

In [205]:
rfe.support_

array([ True,  True, False,  True])

# Task 5.
Given a BookMyShow movie ratings dataset, detect outliers in the 'user ratings' column using the IQR method. Remove the outliers and display how many rows were dropped.<br><br><em><strong>Hint:</strong> Calculate Q1, Q3, and IQR; filter out rows outside [Q1 - 1.5*IQR, Q3 + 1.5*IQR].</em>

In [209]:
df=pd.read_csv(r"C:\Users\DHRUV MODI\Documents\TOPS\Data set\movie dataset rating\Movie-Dataset-Latest.csv")
df.head()

,Unnamed: 0,id,title,release_date,overview,popularity,vote_average,vote_count,video
0,0,19404,Dilwale Dulhania Le Jayenge,1995-10-20,"Raj is a rich, carefree, happy-go-lucky second...",25.884,8.7,3304,False
1,1,278,The Shawshank Redemption,1994-09-23,Framed in the 1940s for the double murder of h...,60.110,8.7,20369,False
2,2,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",62.784,8.7,15219,False
3,3,724089,Gabriel's Inferno Part II,2020-07-31,Professor Gabriel Emerson finally learns the t...,28.316,8.6,1360,False
4,4,424,Schindler's List,1993-11-30,The true story of how businessman Oskar Schind...,38.661,8.6,12158,False

In [210]:
q1 = df['vote_average'].quantile(0.25)
q3 = df['vote_average'].quantile(0.75)
iqr = q3 - q1

In [211]:
q1,q3,iqr

(np.float64(6.1), np.float64(7.2), np.float64(1.1000000000000005))

In [213]:
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr
lower_bound,upper_bound

(np.float64(4.449999999999999), np.float64(8.850000000000001))

In [215]:
df_filtered = df[(df['vote_average'] >= lower_bound) & (df['vote_average'] <= upper_bound)]
df_filtered

,Unnamed: 0,id,title,release_date,overview,popularity,vote_average,vote_count,video
0,0,19404,Dilwale Dulhania Le Jayenge,1995-10-20,"Raj is a rich, carefree, happy-go-lucky second...",25.884,8.7,3304,False
1,1,278,The Shawshank Redemption,1994-09-23,Framed in the 1940s for the double murder of h...,60.110,8.7,20369,False
2,2,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",62.784,8.7,15219,False
3,3,724089,Gabriel's Inferno Part II,2020-07-31,Professor Gabriel Emerson finally learns the t...,28.316,8.6,1360,False
4,4,424,Schindler's List,1993-11-30,The true story of how businessman Oskar Schind...,38.661,8.6,12158,False
...,...,...,...,...,...,...,...,...,...
9366,9366,15206,The Mother of Tears,2007-09-06,An ancient urn is found in a cemetery outside ...,4.209,4.5,330,False
9367,9367,28739,Cabin Fever 2: Spring Fever,2009-08-11,A high school prom faces a deadly threat: a fl...,9.815,4.5,256,False
9368,9368,332,Inspector Gadget,1999-07-23,John Brown is a bumbling but well-intentioned ...,9.995,4.5,931,False
9369,9369,26264,George of the Jungle 2,2003-08-18,"George and Ursula now have a son, George Junio...",15.671,4.5,377,False
9370,9370,472838,SPF-18,2017-09-29,18-year-old Penny Cooper spent years pining fo...,17.546,4.5,967,False

In [216]:
rows_dropped = len(df) - len(df_filtered)
rows_dropped

92